//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID_Application { get; set; }
        public Nullable<int> ID_Artiat { get; set; }
        public Nullable<System.DateTime> Date_Application { get; set; }
        public string Description { get; set; }
        public string StatusApplication { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
