//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Trainer
    {
        public int ID_Schedule_Trainer { get; set; }
        public Nullable<int> ID_Trainer { get; set; }
        public Nullable<int> ID_Cell { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Hour { get; set; }
        public string Name_Status { get; set; }
    
        public virtual Cell Cell { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
